# Copyright (C) 2026 Luis Arturo Pacheco
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Animaquina Core — KUKA Dynamic Sync KRL program generator
# Generates mq_stream.src, mq_stream.dat, and a $CONFIG.DAT snippet.
#
# C3 Bridge / KukavarProxy can only read/write GLOBAL variables (system vars
# and those declared in $CONFIG.DAT).  Program-local variables in a .dat file
# are invisible to cross-comm.  Therefore all MQ_ variables that Blender needs
# to read or write must live in $CONFIG.DAT on the robot.
#
# REFERENCE: old addon set_start_parameters uses FDAT_ACT + BAS(#PTP_PARAMS).
# KRL has no ELSEIF — use independent IF/ENDIF blocks.
# KRL has no MOD — use wrap-around counter for ring index.

PROGRAM_NAME = "mq_stream"
RING_BUFFER_SIZE_DEFAULT = 6
# Advance-run lookahead ($ADVANCE). Keep strictly below the ring buffer size so
# the planner never swallows the whole buffer before the producer can refill it
# (a 1:1 advance:buffer ratio causes the start-of-path stall). Default 3 = KUKA
# default, plenty for C_DIS/C_PTP blending, and leaves margin against buffer 6.
ADVANCE_DEFAULT = 3


def generate_config_snippet(base_no: int = 0, tool_no: int = 0, ring_buffer_size: int = RING_BUFFER_SIZE_DEFAULT) -> str:
    """Return the lines the user must add to the USER GLOBALS section of
    KRC:\\R1\\System\\$CONFIG.DAT.
    These make the MQ_ and E_ variables globally accessible for C3 Bridge."""
    lines = [
        "",
        "; ── Animaquina Dynamic Sync (add to USER GLOBALS in $CONFIG.DAT) ──",
        "",
        "; Command from Blender: 0=idle 1=PTP_joints 2=LIN_cart 3=PTP_cart",
        ";   10=queue_LIN 11=queue_PTP 20=puppet_PTP 99=exit",
        "DECL INT MQ_ACTION = 0",
        "",
        "; Handshake counters",
        "DECL INT MQ_CMD_ID = 0",
        "DECL INT MQ_DONE_ID = 0",
        "",
        "; Single-move targets (FRAME — no S/T, reliable via C3 Bridge)",
        "DECL E6AXIS MQ_E6AXIS = {A1 0, A2 0, A3 0, A4 0, A5 0, A6 0}",
        "DECL FRAME  MQ_E6POS  = {X 0, Y 0, Z 0, A 0, B 0, C 0}",
        "",
        "; Speed / approximation",
        "DECL REAL MQ_SPEED   = 15",
        "DECL REAL MQ_LIN_VEL = 0.05",
        "DECL REAL MQ_APO     = -1",
        "DECL REAL MQ_PUPPET_SPEED = 50    ; PTP speed % for puppet mode (0.1–100)",
        "",
        "; Base / Tool selection",
        "DECL INT MQ_BASE_NO = " + str(base_no),
        "DECL INT MQ_TOOL_NO = " + str(tool_no),
        "",
        "; Ring buffer for queued path points (1-based, size " + str(ring_buffer_size) + ")",
        "DECL FRAME MQ_PT[" + str(ring_buffer_size) + "]",
        "DECL INT MQ_WR_IDX  = 0",
        "DECL INT MQ_RD_IDX  = 0",
        "DECL INT MQ_PT_CNT  = 0",
        "",
        "; State feedback: 0=idle 1=moving 2=error 3=queue_active",
        "DECL INT MQ_STATE = 0",
        "",
        "; ── Animaquina end-effector globals ──",
        "DECL INT  IDX      = 0      ; Current waypoint index (robot writes, Blender reads)",
        "DECL BOOL E_ENABLE = FALSE",
        "DECL REAL E_SPEED  = 0.0",
        "DECL REAL E_FLOW   = 0.0",
        "DECL REAL E_TEMP   = 0.0",
        "DECL REAL F_SPEED  = 0.0    ; Fan speed",
        "",
        "; ── End Animaquina ──",
    ]
    return "\n".join(lines) + "\n"


def generate_dat() -> str:
    """Return mq_stream.dat — only program-internal variables.
    All cross-comm MQ_ variables live in $CONFIG.DAT instead."""
    lines = [
        "&ACCESS RVO",
        "&REL 1",
        "DEFDAT " + PROGRAM_NAME + " PUBLIC",
        "",
        "; Program-internal only (cross-comm vars are in $CONFIG.DAT)",
        "DECL BOOL MQ_LOOP = TRUE",
        "DECL INT MQ_I = 0",
        "",
        "ENDDAT",
    ]
    return "\n".join(lines) + "\n"


def generate_src(base_no: int = 0, tool_no: int = 0, ring_buffer_size: int = RING_BUFFER_SIZE_DEFAULT,
                 advance: int = ADVANCE_DEFAULT) -> str:
    """Return mq_stream.src content (main program).
    MQ_ variables are resolved from $CONFIG.DAT (global scope).
    Uses independent IF/ENDIF blocks (KRL has no ELSEIF).

    advance sets $ADVANCE (planner lookahead). It is clamped to [1, 5] (KUKA range)
    and to ring_buffer_size-1 so the advance run cannot drain the whole ring buffer."""
    bs = str(ring_buffer_size)
    adv = max(1, min(5, int(advance)))
    # Never let the planner look further ahead than the producer can keep filled.
    adv = min(adv, max(1, int(ring_buffer_size) - 1))
    lines = [
        "&ACCESS RVP",
        "&REL 1",
        "&PARAM TEMPLATE = C:\\KRC\\Roboter\\Template\\vorgabe",
        "&PARAM EDITMASK = *",
        "DEF " + PROGRAM_NAME + "()",
        "",
        ";FOLD INI",
        ";FOLD BASISTECH INI",
        "GLOBAL INTERRUPT DECL 3 WHEN $STOPMESS==TRUE DO IR_STOPM()",
        "INTERRUPT ON 3",
        "BAS(#INITMOV, 0)",
        ";ENDFOLD (BASISTECH INI)",
        ";ENDFOLD (INI)",
        "",
        ";FOLD STARTPOSITION - BASE IS " + str(base_no) + ", TOOL IS " + str(tool_no) + ", SPEED IS 15%",
        "$BWDSTART = FALSE",
        "PDAT_ACT = {VEL 15, ACC 100, APO_DIST 50}",
        "FDAT_ACT = {TOOL_NO " + str(tool_no) + ", BASE_NO " + str(base_no) + ", IPO_FRAME #BASE}",
        "BAS(#PTP_PARAMS, 15)",
        ";ENDFOLD",
        "",
        "; First motion — PTP to current position (required by KRC before any other move)",
        "PTP $AXIS_ACT",
        "",
        "$VEL.CP = MQ_LIN_VEL",
        "$ADVANCE = " + str(adv),
        "",
        "; Init ring buffer (after first motion so KRC is satisfied)",
        "FOR MQ_I = 1 TO " + bs,
        "    MQ_PT[MQ_I] = {X 0, Y 0, Z 0, A 0, B 0, C 0}",
        "ENDFOR",
        "",
        "; Reset state",
        "MQ_STATE   = 0",
        "MQ_DONE_ID = 0",
        "MQ_LOOP    = TRUE",
        "MQ_I       = 0",
        "",
        "; -- Main command loop --",
        "; Each IF block is independent (KRL has no ELSEIF).",
        "; Handlers set MQ_ACTION=0, so only one block runs per iteration.",
        "WHILE MQ_LOOP",
        "",
        "    IF MQ_ACTION == 1 THEN",
        "        MQ_STATE = 1",
        "        IF MQ_APO >= 0 THEN",
        "            $APO.CPTP = MQ_APO",
        "            PTP MQ_E6AXIS C_PTP",
        "        ELSE",
        "            PTP MQ_E6AXIS",
        "        ENDIF",
        "        MQ_DONE_ID = MQ_CMD_ID",
        "        MQ_STATE   = 0",
        "        MQ_ACTION  = 0",
        "    ENDIF",
        "",
        "    IF MQ_ACTION == 2 THEN",
        "        MQ_STATE = 1",
        "        $VEL.CP  = MQ_LIN_VEL",
        "        IF MQ_APO >= 0 THEN",
        "            $APO.CDIS = MQ_APO",
        "            LIN MQ_E6POS C_DIS",
        "        ELSE",
        "            LIN MQ_E6POS",
        "        ENDIF",
        "        MQ_DONE_ID = MQ_CMD_ID",
        "        MQ_STATE   = 0",
        "        MQ_ACTION  = 0",
        "    ENDIF",
        "",
        "    IF MQ_ACTION == 3 THEN",
        "        MQ_STATE = 1",
        "        BAS(#PTP_PARAMS, MQ_SPEED)",
        "        IF MQ_APO >= 0 THEN",
        "            $APO.CPTP = MQ_APO",
        "            PTP MQ_E6POS C_PTP",
        "        ELSE",
        "            PTP MQ_E6POS",
        "        ENDIF",
        "        MQ_DONE_ID = MQ_CMD_ID",
        "        MQ_STATE   = 0",
        "        MQ_ACTION  = 0",
        "    ENDIF",
        "",
        "    IF MQ_ACTION == 10 THEN",
        "        MQ_STATE = 3",
        "        MQ_I     = 0",
        "        IDX      = 0",
        "        $VEL.CP  = MQ_LIN_VEL",
        "        IF MQ_APO >= 0 THEN",
        "            $APO.CDIS = MQ_APO",
        "        ENDIF",
        "",
        "        WHILE MQ_RD_IDX <> MQ_WR_IDX",
        "            MQ_I = MQ_I + 1",
        "            IF MQ_I > " + bs + " THEN",
        "                MQ_I = 1",
        "            ENDIF",
        "            ; Path-synchronous waypoint counter. MQ_RD_IDX below is a plain",
        "            ; assignment, so it runs in the ADVANCE run - up to $ADVANCE",
        "            ; motion blocks ahead of the robot. Blender needs an index that",
        "            ; tracks PHYSICAL motion to switch the end effector in sync, so",
        "            ; IDX is incremented by a TRIGGER, which executes in the main run",
        "            ; when the robot actually starts into this waypoint.",
        "            TRIGGER WHEN DISTANCE=0 DELAY=0 DO IDX = IDX + 1",
        "            IF MQ_APO >= 0 THEN",
        "                IF MQ_RD_IDX < MQ_PT_CNT THEN",
        "                    LIN MQ_PT[MQ_I] C_DIS",
        "                ELSE",
        "                    LIN MQ_PT[MQ_I]",
        "                ENDIF",
        "            ELSE",
        "                LIN MQ_PT[MQ_I]",
        "            ENDIF",
        "            MQ_RD_IDX = MQ_RD_IDX + 1",
        "            IF (MQ_RD_IDX == MQ_WR_IDX) AND (MQ_RD_IDX < MQ_PT_CNT) THEN",
        "                WAIT FOR MQ_WR_IDX > MQ_RD_IDX",
        "            ENDIF",
        "        ENDWHILE",
        "",
        "        MQ_DONE_ID = MQ_CMD_ID",
        "        MQ_STATE   = 0",
        "        MQ_ACTION  = 0",
        "    ENDIF",
        "",
        "    IF MQ_ACTION == 11 THEN",
        "        MQ_STATE = 3",
        "        MQ_I     = 0",
        "        IDX      = 0",
        "        BAS(#PTP_PARAMS, MQ_SPEED)",
        "        IF MQ_APO >= 0 THEN",
        "            $APO.CPTP = MQ_APO",
        "        ENDIF",
        "",
        "        WHILE MQ_RD_IDX <> MQ_WR_IDX",
        "            MQ_I = MQ_I + 1",
        "            IF MQ_I > " + bs + " THEN",
        "                MQ_I = 1",
        "            ENDIF",
        "            ; Path-synchronous waypoint counter. MQ_RD_IDX below is a plain",
        "            ; assignment, so it runs in the ADVANCE run - up to $ADVANCE",
        "            ; motion blocks ahead of the robot. Blender needs an index that",
        "            ; tracks PHYSICAL motion to switch the end effector in sync, so",
        "            ; IDX is incremented by a TRIGGER, which executes in the main run",
        "            ; when the robot actually starts into this waypoint.",
        "            TRIGGER WHEN DISTANCE=0 DELAY=0 DO IDX = IDX + 1",
        "            IF MQ_APO >= 0 THEN",
        "                IF MQ_RD_IDX < MQ_PT_CNT THEN",
        "                    PTP MQ_PT[MQ_I] C_PTP",
        "                ELSE",
        "                    PTP MQ_PT[MQ_I]",
        "                ENDIF",
        "            ELSE",
        "                PTP MQ_PT[MQ_I]",
        "            ENDIF",
        "            MQ_RD_IDX = MQ_RD_IDX + 1",
        "            IF (MQ_RD_IDX == MQ_WR_IDX) AND (MQ_RD_IDX < MQ_PT_CNT) THEN",
        "                WAIT FOR MQ_WR_IDX > MQ_RD_IDX",
        "            ENDIF",
        "        ENDWHILE",
        "",
        "        MQ_DONE_ID = MQ_CMD_ID",
        "        MQ_STATE   = 0",
        "        MQ_ACTION  = 0",
        "    ENDIF",
        "",
        "    ; ── Puppet mode (tight PTP loop, like C3BI_JOG) ──",
        "    ; Safe: absolute PTP — on connection loss robot stays at last pose.",
        "    ; Blender sets MQ_ACTION=0 to exit cleanly.",
        "    IF MQ_ACTION == 20 THEN",
        "        MQ_STATE = 1",
        "        BAS(#PTP_PARAMS, MQ_PUPPET_SPEED)",
        "        $ADVANCE = 1",
        "",
        "        WHILE MQ_ACTION == 20",
        "            CONTINUE",
        "            PTP MQ_E6POS C_PTP",
        "        ENDWHILE",
        "",
        "        MQ_STATE = 0",
        "    ENDIF",
        "",
        "    IF MQ_ACTION == 99 THEN",
        "        MQ_LOOP = FALSE",
        "    ENDIF",
        "",
        "    IF MQ_ACTION == 0 THEN",
        "        WAIT SEC 0.01",
        "    ENDIF",
        "",
        "ENDWHILE",
        "",
        "MQ_STATE = 0",
        "END",
    ]
    return "\n".join(lines) + "\n"
